/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stock;


import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.ResultSetMetaData;
import java.awt.Color;
import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Ravindu. Madusanka
 */
public class stock_release extends javax.swing.JFrame {

    /**
     * Creates new form catogory
     */
    public stock_release() {
        initComponents();
        table_update();
    }
    
    Connection con;
    PreparedStatement pst;
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpmenulist = new javax.swing.JPanel();
        jpsr = new javax.swing.JPanel();
        jl1 = new javax.swing.JLabel();
        jpcr = new javax.swing.JPanel();
        jl3 = new javax.swing.JLabel();
        jppr = new javax.swing.JPanel();
        jl2 = new javax.swing.JLabel();
        jpstbtn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtpprice = new javax.swing.JTextField();
        txtpid = new javax.swing.JTextField();
        txtpname = new javax.swing.JTextField();
        txtpstock = new javax.swing.JTextField();
        addbtn = new javax.swing.JButton();
        editbtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ptable = new javax.swing.JTable();
        jpprbtn = new javax.swing.JPanel();
        txtpid1 = new javax.swing.JTextField();
        addbtn2 = new javax.swing.JButton();
        editbtn2 = new javax.swing.JButton();
        deletebtn2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        jpmenulist.setBackground(new java.awt.Color(51, 51, 51));

        jpsr.setBackground(new java.awt.Color(115, 109, 109));
        jpsr.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpsrMouseMoved(evt);
            }
        });
        jpsr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpsrMouseClicked(evt);
            }
        });

        jl1.setFont(new java.awt.Font("Viking Squad", 0, 36)); // NOI18N
        jl1.setText("STOCK RELEASE");

        javax.swing.GroupLayout jpsrLayout = new javax.swing.GroupLayout(jpsr);
        jpsr.setLayout(jpsrLayout);
        jpsrLayout.setHorizontalGroup(
            jpsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpsrLayout.setVerticalGroup(
            jpsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        jpcr.setBackground(new java.awt.Color(70, 70, 70));
        jpcr.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpcrMouseMoved(evt);
            }
        });
        jpcr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpcrMouseClicked(evt);
            }
        });

        jl3.setFont(new java.awt.Font("Viking Squad", 0, 30)); // NOI18N
        jl3.setText("COUSTOMER REGISTRY");

        javax.swing.GroupLayout jpcrLayout = new javax.swing.GroupLayout(jpcr);
        jpcr.setLayout(jpcrLayout);
        jpcrLayout.setHorizontalGroup(
            jpcrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpcrLayout.setVerticalGroup(
            jpcrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl3, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        jppr.setBackground(new java.awt.Color(70, 70, 70));
        jppr.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpprMouseMoved(evt);
            }
        });
        jppr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpprMouseClicked(evt);
            }
        });

        jl2.setFont(new java.awt.Font("Viking Squad", 0, 30)); // NOI18N
        jl2.setText("PRODUCT REGISTRY");

        javax.swing.GroupLayout jpprLayout = new javax.swing.GroupLayout(jppr);
        jppr.setLayout(jpprLayout);
        jpprLayout.setHorizontalGroup(
            jpprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpprLayout.setVerticalGroup(
            jpprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jl2, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpmenulistLayout = new javax.swing.GroupLayout(jpmenulist);
        jpmenulist.setLayout(jpmenulistLayout);
        jpmenulistLayout.setHorizontalGroup(
            jpmenulistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jppr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpsr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpcr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpmenulistLayout.setVerticalGroup(
            jpmenulistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpmenulistLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jppr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpcr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpstbtn.setBackground(new java.awt.Color(115, 109, 109));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Product Name");
        jLabel1.setMaximumSize(new java.awt.Dimension(82, 22));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Stock");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Product Price");

        addbtn.setText("ADD");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        editbtn.setText("EDIT");
        editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbtnActionPerformed(evt);
            }
        });

        deletebtn.setText("DELETE");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Product ID");

        ptable.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        ptable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Product ID", "Product Name", "Product Price", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ptable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ptableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ptable);
        if (ptable.getColumnModel().getColumnCount() > 0) {
            ptable.getColumnModel().getColumn(0).setResizable(false);
            ptable.getColumnModel().getColumn(1).setResizable(false);
            ptable.getColumnModel().getColumn(2).setResizable(false);
            ptable.getColumnModel().getColumn(2).setPreferredWidth(120);
            ptable.getColumnModel().getColumn(3).setResizable(false);
            ptable.getColumnModel().getColumn(3).setPreferredWidth(120);
            ptable.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout jpstbtnLayout = new javax.swing.GroupLayout(jpstbtn);
        jpstbtn.setLayout(jpstbtnLayout);
        jpstbtnLayout.setHorizontalGroup(
            jpstbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpstbtnLayout.createSequentialGroup()
                .addGroup(jpstbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpstbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jpstbtnLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtpstock, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                        .addGroup(jpstbtnLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(jpstbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(4, 4, 4)
                            .addGroup(jpstbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtpname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                .addComponent(txtpid, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtpprice))))
                    .addGroup(jpstbtnLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpstbtnLayout.setVerticalGroup(
            jpstbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpstbtnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpstbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpstbtnLayout.createSequentialGroup()
                        .addGroup(jpstbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpid, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jpstbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(txtpname))
                        .addGap(30, 30, 30)
                        .addGroup(jpstbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpprice, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jpstbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpstock, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpstbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 151, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jpprbtn.setBackground(new java.awt.Color(115, 109, 109));

        addbtn2.setText("ADD");
        addbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtn2ActionPerformed(evt);
            }
        });

        editbtn2.setText("EDIT");
        editbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbtn2ActionPerformed(evt);
            }
        });

        deletebtn2.setText("DELETE");
        deletebtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtn2ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("rvd");

        jLabel2.setFont(new java.awt.Font("TESLA", 0, 48)); // NOI18N
        jLabel2.setText("RAVINDU");

        javax.swing.GroupLayout jpprbtnLayout = new javax.swing.GroupLayout(jpprbtn);
        jpprbtn.setLayout(jpprbtnLayout);
        jpprbtnLayout.setHorizontalGroup(
            jpprbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpprbtnLayout.createSequentialGroup()
                .addGroup(jpprbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpprbtnLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(txtpid1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpprbtnLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(addbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deletebtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpprbtnLayout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        jpprbtnLayout.setVerticalGroup(
            jpprbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpprbtnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpprbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpid1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jpprbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(deletebtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(161, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpmenulist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpstbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 236, Short.MAX_VALUE)
                    .addComponent(jpprbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpmenulist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpstbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpprbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void table_update()
    {
        try {
            int c;
            try {
                Class.forName("com.mysql.jdbc.Driver");
                con =(Connection) DriverManager.getConnection("jdbc:mysql://localhost/stock_mgt","root","");
                pst = (PreparedStatement) con.prepareStatement("select * from pr_reg");
                ResultSet rs =pst.executeQuery();
                
                ResultSetMetaData rsd = (ResultSetMetaData) rs.getMetaData();
                c = rsd.getColumnCount();
                
                DefaultTableModel d = (DefaultTableModel)ptable.getModel();
                d.setRowCount(0);
                              
                while(rs.next())
                {
                    Vector v2 = new  Vector();
                  
                        for(int i=1; i<=c; i++)
                        {   
                            v2.add(rs.getInt("id"));
                            v2.add(rs.getString("product_id"));
                            v2.add(rs.getString("product_name"));                            
                            v2.add(rs.getDouble("product_price"));
                            v2.add(rs.getInt("stock"));
                            
                        }
                        
                        d.addRow(v2);                   
                }                                                    
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(stock_release.class.getName()).log(Level.SEVERE, null, ex);
            }                      
        } catch (SQLException ex) {
            Logger.getLogger(stock_release.class.getName()).log(Level.SEVERE, null, ex);
        }            
    }

    private void editbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbtnActionPerformed
        
        DefaultTableModel d = (DefaultTableModel)ptable.getModel();
        int selectIndex = ptable.getSelectedRow();
        
        int id = Integer.parseInt(d.getValueAt(selectIndex,0).toString());         
        String pid = txtpid.getText();                 
        String pname = txtpname.getText();
        String pprice = txtpprice.getText();
        String pstock = txtpstock.getText();
        
            try {
            Class.forName("com.mysql.jdbc.Driver");
            con =(Connection) DriverManager.getConnection("jdbc:mysql://localhost/stock_mgt","root","");
            pst =(PreparedStatement) con.prepareStatement("update pr_reg set product_id=? , product_name=? , product_price=? , stock=? where id=? ");
            
            pst.setString(1, pid);
            pst.setString(2, pname);
            pst.setString(3, pprice);
            pst.setString(4, pstock);
            pst.setInt(5, id);
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Catogory Updated");
            table_update();
                          
            txtpid.setText("");
            txtpname.setText("");
            txtpprice.setText("");
            txtpstock.setText("");
            
            txtpid.requestFocus();
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(stock_release.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_editbtnActionPerformed

    private void ptableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ptableMouseClicked

        DefaultTableModel d = (DefaultTableModel)ptable.getModel();
        int selectIndex = ptable.getSelectedRow();

        txtpid.setText(d.getValueAt(selectIndex, 1).toString());
        txtpname.setText(d.getValueAt(selectIndex, 2).toString());
        txtpprice.setText(d.getValueAt(selectIndex, 3).toString());
        txtpstock.setText(d.getValueAt(selectIndex, 4).toString());

    }//GEN-LAST:event_ptableMouseClicked

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
       
        DefaultTableModel d = (DefaultTableModel)ptable.getModel();
        int selectIndex = ptable.getSelectedRow();
        
        int id = Integer.parseInt(d.getValueAt(selectIndex,0).toString());
        
        int dialogResult = JOptionPane.showConfirmDialog(null,"Dou you want to delete the record","Warning",JOptionPane.YES_NO_OPTION);
        
        if(dialogResult == JOptionPane.YES_OPTION)
        {
            try {
            Class.forName("com.mysql.jdbc.Driver");
            con =(Connection) DriverManager.getConnection("jdbc:mysql://localhost/stock_mgt","root","");
            pst =(PreparedStatement) con.prepareStatement("delete from pr_reg where id=? ");
    
            pst.setInt(1, id);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Catogory Deleted");
            table_update();
                          
            txtpid.setText("");
            txtpname.setText("");
            txtpprice.setText("");
            txtpstock.setText("");
            
            txtpid.requestFocus();
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(stock_release.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        }
        
        
    }//GEN-LAST:event_deletebtnActionPerformed

    private void jpsrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpsrMouseClicked
        
        jpstbtn.setVisible(true);
        jpprbtn.setVisible(false);
        setColor(jpsr);
        resetColor(jppr);
        resetColor(jpcr);
    }//GEN-LAST:event_jpsrMouseClicked

    private void jpsrMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpsrMouseMoved
        
        setColor(jpsr);
        resetColor(jppr);
        resetColor(jpcr);
    }//GEN-LAST:event_jpsrMouseMoved

    private void jpprMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpprMouseClicked
        
        jpprbtn.setVisible(true);
        jpstbtn.setVisible(false);
        setColor(jppr);
        resetColor(jpsr);
        resetColor(jpcr);
    }//GEN-LAST:event_jpprMouseClicked

    private void jpprMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpprMouseMoved
        
        setColor(jppr);
        resetColor(jpsr);
        resetColor(jpcr);
    }//GEN-LAST:event_jpprMouseMoved

    private void jpcrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpcrMouseClicked
        
        setColor(jpcr);
        resetColor(jpsr);
        resetColor(jppr);
    }//GEN-LAST:event_jpcrMouseClicked

    private void jpcrMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpcrMouseMoved
        
        setColor(jpcr);
        resetColor(jpsr);
        resetColor(jppr);
    }//GEN-LAST:event_jpcrMouseMoved

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        // TODO add your handling code here:

        String pid = txtpid.getText();
        String pname = txtpname.getText();
        String pprice = txtpprice.getText();
        String pstock = txtpstock.getText();

        try {
            Class.forName("com.mysql.jdbc.Driver");
            con =(Connection) DriverManager.getConnection("jdbc:mysql://localhost/stock_mgt","root","");
            pst =(PreparedStatement) con.prepareStatement("insert into pr_reg(product_id,product_name,product_price,stock)values(?,?,?,?)");
            pst.setString(1, pid);
            pst.setString(2, pname);
            pst.setString(3, pprice);
            pst.setString(4, pstock);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Catogory Added");
            table_update();

            txtpid.setText("");
            txtpname.setText("");
            txtpprice.setText("");
            txtpstock.setText("");

            txtpid.requestFocus();

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(stock_release.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_addbtnActionPerformed

    private void deletebtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deletebtn2ActionPerformed

    private void editbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editbtn2ActionPerformed

    private void addbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addbtn2ActionPerformed
    
    void setColor(JPanel panel)
    {
        panel.setBackground (new Color(115,109,109));
    }
    
    void resetColor(JPanel panel)
    {
        panel.setBackground (new Color(70,70,70));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stock_release.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stock_release.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stock_release.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stock_release.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stock_release().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JButton addbtn2;
    private javax.swing.JButton deletebtn;
    private javax.swing.JButton deletebtn2;
    private javax.swing.JButton editbtn;
    private javax.swing.JButton editbtn2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jl1;
    private javax.swing.JLabel jl2;
    private javax.swing.JLabel jl3;
    private javax.swing.JPanel jpcr;
    private javax.swing.JPanel jpmenulist;
    private javax.swing.JPanel jppr;
    private javax.swing.JPanel jpprbtn;
    private javax.swing.JPanel jpsr;
    private javax.swing.JPanel jpstbtn;
    private javax.swing.JTable ptable;
    private javax.swing.JTextField txtpid;
    private javax.swing.JTextField txtpid1;
    private javax.swing.JTextField txtpname;
    private javax.swing.JTextField txtpprice;
    private javax.swing.JTextField txtpstock;
    // End of variables declaration//GEN-END:variables

    private void getConnection(String jdbcmysqllocalhoststock_mgt, String root, String string) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
